services:
  - type: web
    name: noris2026
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npx vite preview --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./client/dist

